config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :food_items, only: [:index, :create, :destroy, :update]
    end
  end

  resources :food_items do
    resources :orders
    resources :reviews
  end

  resources :welcome
  
  resources :menu do
    collection do
      get :lowhighprice 
      get :highlowprice
      get :abc
    end
  end
  
  get 'menu' => 'menu#index'
  get 'contact_us' => 'welcome#contact_us'
  get 'react' => 'welcome#react'

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  

  def index
  
  # @food_items = FoodItem.all
	
  if params[:search]
      @food_items = FoodItem.where(
       "lower(name) LIKE lower(?)",
       "%#{Regexp.escape(params[:search])}%"
       )
      params[:section]
      @sections = %w(Breakfast Lunch Dinner Drinks)
      # if @food_items.nil
      #   @sorry = "Sorry! No item found"
      # end
      # @food_items.class == Array
      # @food_items = Kaminari.paginate_array(@food_items).page(params[:page]).per(5)
          # else
      # @food_items = FoodItem.all.order("created_at DESC").page(params[:page]).per(5)
      render 'index'
    else
    	params[:section]
    	@sections = %w(Breakfast Lunch Dinner Drinks)

  		@food_items = FoodItem.where(section: params[:section]).order("created_at DESC")
  		# @food_items.class == Array
  		# @food_items = Kaminari.paginate_array(@food_items).page(params[:page]).per(5)
  		if params[:section] == nil
  			@food_items = FoodItem.all
      	end
  		# @food_items = FoodItem.by_section(params:[section])
  	 end
  end


	def show		
	end


	def lowhighprice
    params[:section]
    @sections = %w(Breakfast Lunch Dinner Drinks)
    
    @food_items = FoodItem.lowhighprice
    render action: :index
  end

  def highlowprice
    params[:section]
    @sections = %w(Breakfast Lunch Dinner Drinks)
    
    @food_items = FoodItem.highlowprice
    render action: :index
  end

  def abc
    sectionz
    @food_items = FoodItem.abc
    render action: :index
  end

  private
    def sectionz
      params[:section]
      @sections = %w(Breakfast Lunch Dinner Drinks)
    end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/index.html.haml
%h1 Menu

.container
	.row
		%ul.nav.nav-pills
			= @sections.each do |section|
				%li.nav-item
					= link_to section, menu_index_path(section: section), class: "nav-link #{params[:section] == section && 'active'}"
			%li.nav-item
				Sort by:
			%li.nav-item
				= link_to "High To Low Price", highlowprice_menu_index_path, class: 'btn btn-secondary'
			%li.nav-item
				= link_to "Low To High Price", lowhighprice_menu_index_path, class: 'btn btn-secondary'
			%li.nav-item
				= link_to "Alphabetical", abc_menu_index_path, class: 'btn btn-secondary'	
	%br
	%br
		- if (@food_items.empty?)
			%h2 Sorry, no food found :(
		- else  
	/ = paginate @food_items

.container
	.col-xs-12
		.row
			- @food_items.each do |food_item|
				.col-xs-6
					.card.card-inverse
						%img.card-img{:alt => "Food Image", "src" => "#{food_item.image_url}", :width => "100%"}
						.card-img-overlay
							%h4.card-title 
								= link_to food_item.name, food_item
							%p.card-text #{food_item.description}
							%p.card-text VND #{food_item.price}
							= link_to "Order", new_food_item_order_path(food_item), class: 'btn btn-success'

/ = @food_items.in_groups_of(3) do |group|
/ .row
/ = group.compact.each do |food_item|
/ - @food_items.each do |food_item|
/ .col-xs-6
/ .card.card-inverse
/ %img.card-img{:alt => "Food Image", "src" => "#{food_item.image_url}", :width => "100%"}
/ .card-img-overlay
/ %h4.card-title 
/ = link_to food_item.name, food_item
/ %p.card-text #{food_item.description}
/ %p.card-text VND #{food_item.price}
/ = link_to "Order", menu_index_path, class: 'btn btn-success'

app/views/menu/indexbak.haml
:javascript
	$(document).on('ready page:load', function () {
		$("#breakfast").click(function(){
		  $(".lunch").hide();
		  $(".dinner").hide();
		  $(".drinks").hide();
		  $(".show").show();
		});
		$("#show").click(function(){
		  $("p").show();
		});
	});




.col-xs-12
	%h1 Menu

	- if (@food_items.empty?)
		%h2 Sorry, no food found :(
	- else

.btn-group{"aria-label" => "Sections", :role => "group"}
	%button#breakfast.btn.btn-secondary Breakfast
	%button#lunch.btn.btn-secondary Lunch
	%button#dinner.btn.btn-secondary Dinner
	%button#drinks.btn.btn-secondary Drinks
%br
%br

.col-xs-12
	.row
		.services
			%ul#accordion1.nav.nav-stacked
				%li.panel
					%a{"data-parent" => "#accordion1", "data-toggle" => "collapse", :href => "#Audit"} Accounding and Audit
				%ul#Audit.collapse
					%li Audit & Taxation
	          
.col-xs-12
	.row
		- @food_items.each do |food_item|
			.col-xs-6
				.card.card-inverse
					%img.card-img{:alt => "Food Image", "src" => "#{food_item.image_url}", :width => "100%"}
					.card-img-overlay
						%h4.card-title 
							= link_to food_item.name, food_item
						%p.card-text #{food_item.description}
						%p.card-text VND #{food_item.price}
						= link_to "Order", new_food_item_order_path(food_item), class: 'btn btn-success'

/ = @food_items.in_groups_of(3) do |group|
/ .row
/ = group.compact.each do |food_item|
/ - @food_items.each do |food_item|
/ .col-xs-6
/ .card.card-inverse
/ %img.card-img{:alt => "Food Image", "src" => "#{food_item.image_url}", :width => "100%"}
/ .card-img-overlay
/ %h4.card-title 
/ = link_to food_item.name, food_item
/ %p.card-text #{food_item.description}
/ %p.card-text VND #{food_item.price}
/ = link_to "Order", menu_index_path, class: 'btn btn-success'