config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :food_items, only: [:index, :create, :destroy, :update]
    end
  end

  resources :food_items do
    resources :orders
    resources :reviews
  end

  resources :welcome
  
  resources :menu do
    collection do
      get :lowhighprice 
      get :highlowprice
      get :abc
    end
  end
  
  get 'menu' => 'menu#index'
  get 'contact_us' => 'welcome#contact_us'
  get 'react' => 'welcome#react'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	# layout nil
	# layout 'application', :except => :index

	def index
		@food_items = FoodItem.all
		render layout: false
		
		if params[:search]
	      @food_items = FoodItem.where(
	       "lower(name) LIKE lower(?)",
	       "%#{Regexp.escape(params[:search])}%"
	       )
	      # @food_items.class == Array
	      # @food_items = Kaminari.paginate_array(@food_items).page(params[:page]).per(5)
	      # redirect_to menu_index_path 
	    # else
	    #   @food_items = FoodItem.all.order("created_at DESC").page(params[:page]).per(5)
	    end
	end

	def contact_us
		if params[:search] # had to put the search here if the user searches from this controller
	      @food_items = FoodItem.where(
	       "lower(name) LIKE lower(?)",
	       "%#{Regexp.escape(params[:search])}%"
	       )
	      # @food_items.class == Array
	      # @food_items = Kaminari.paginate_array(@food_items).page(params[:page]).per(5)
	      redirect_to menu_index_path(params[:search])
		end
	end

	def react
		@food_items = FoodItem.all		
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/contact_us.html.haml
.panel.panel-default
	.panel-heading
		%h2
			Contact us
	.panel-body
		38 Huỳnh Khương Ninh Đa Kao Quận 1 Đa Kao Quận 1 Hồ Chí Minh Vietnam, Vietnam
		
		%iframe{:allowfullscreen => "", :frameborder => "0", :height => "450", :src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2771.350102749559!2d106.69480814613807!3d10.789784568288752!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0xe0305f43f2a71b6c!2sLoving+Hut!5e0!3m2!1sen!2s!4v1457589413854", :style => "border:0", :width => "100%"}

app/views/welcome/index.html.haml
!!!
%html{lang: "en"}

.jumbotron.jumbotron-fluid
  .container
    %h1.display-3 Loving Hut
    %p.lead Vegetarian Restaurant

  .btn-group{"aria-label" => "Navigation", :role => "group"}
    = link_to "Menu", menu_index_path, class: 'btn btn-secondary'
    = link_to "Contact Us", contact_us_path, class: 'btn btn-secondary'

  .row
    %form.col-center
      = form_tag :controller => 'menu', :action => 'index', :method => 'get' do #food_items_path
        %p
        / %input.form-control{:placeholder => "Search", :type => "text"}
        = text_field_tag :search, params[:search], :placeholder => "Type Dish Here"
        %br
        %button.btn.btn-warning{:type => "submit"} Search


  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  
  = csrf_meta_tags

:css
  body {
   background: url('https://upload.wikimedia.org/wikipedia/commons/1/1d/Restaurant_in_The_Mus%C3%A9e_d%27Orsay.jpg') no-repeat center center fixed;
   -webkit-background-size: cover;
   -moz-background-size: cover;
   -o-background-size: cover;
   background-size: cover;
  }

app/views/welcome/react.html.haml
%h3
	This Page allows users to quickly enter the Menu Items without having to reload the page each time, courtesy of React.js. 
%p
	Unfortunately, it doesn't work :(

= react_component 'Main'