config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :food_items, only: [:index, :create, :destroy, :update]
    end
  end

  resources :food_items do
    resources :orders
    resources :reviews
  end

  resources :welcome
  
  resources :menu do
    collection do
      get :lowhighprice 
      get :highlowprice
      get :abc
    end
  end
  
  get 'menu' => 'menu#index'
  get 'contact_us' => 'welcome#contact_us'
  get 'react' => 'welcome#react'

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
	is_impressionable
	has_many :reviews
	
	validates :name, :section, :price, :image_url, presence: true

	scope :abc, ->{ order("name ASC") }
	scope :lowhighprice, ->{ order("price ASC") }
	scope :highlowprice, ->{ order("price DESC") }


	def self.by_section(section)
		where(section: section) #where food_items.section = #{section}
	end

end

app/controllers/api/v1/food_items_controller.rb
class Api::V1::FoodItemsController < Api::V1::BaseController
  def index
    respond_with FoodItem.all
  end

  def create
    respond_with :api, :v1, FoodItem.create(food_item_params)
  end

  def destroy
    respond_with FoodItem.destroy(params[:id])
  end

  def update
    food_item = FoodItem.find(params["id"])
    food_item.update_attributes(food_item_params)
    respond_with food_item, json: food_item
  end

 private

  def food_item_params
    params.require(:food_item).permit(:name, :description, :price, :section, :image_url, :cuisine)
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show, :index]

  def index
    if params[:search]
      @food_items = FoodItem.where(
       "lower(name) LIKE lower(?)",
       "%#{Regexp.escape(params[:search])}%"
       )
    else
      @food_items = FoodItem.all
    end
  end

  def show
    impressionist(@food_item)

    @reviews = Review.find(params[:id])
      if @food_item.reviews.blank? 
        @average_review = 0
      else
        @average_review = @food_item.reviews.average(:rating).round(2)
      end

    if @average_review == nil
        @average_review = 0
      else
        @average_review = @food_item.reviews.average(:rating).round(2)
    end

    if params[:search]
      @food_items = FoodItem.where(
       "lower(name) LIKE lower(?)",
       "%#{Regexp.escape(params[:search])}%"
       )
      params[:section]
      @sections = %w(Breakfast Lunch Dinner Drinks)
      render 'index'
    end
  end

  def new
    @food_item = FoodItem.new
  end

  def edit
  end

  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :image_url, :cuisine)
    end

    def find_review
      @reviews = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:rating, :rev, :food_item_id)
    end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_form.html.haml
= form_for @food_item do |f|
  - if @food_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food_item.errors.count, "error")} prohibited this food_item from being saved:"
      %ul
        - @food_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :section
    = f.select :section, [ 'Breakfast','Lunch','Dinner', 'Drinks' ], :prompt => 'Section'
  .field
    = f.label :cuisine
    = f.text_field :cuisine
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :Coupon
    = f.text_field :coupon

  .actions
    = f.submit 'Save'

app/views/food_items/edit.html.haml
%h1 Editing food_item

= render 'form'

= link_to 'Show', @food_item
\|
= link_to 'Back', food_items_path

app/views/food_items/index.html.haml
%br
%h1 Listing Food Items

%table.table.table-striped.table-condensed
  %thead
    %tr
      %th Name
      %th Description
      %th Price
      %th Section
      %th Image url
      %th Views

  %tbody
    - @food_items.each do |food_item|
      %tr
        %td= food_item.name
        %td= food_item.description
        %td= food_item.price
        %td= food_item.section
        %td= food_item.image_url
        %td= food_item.impressionist_count
        %td= link_to 'Show', food_item
        %td= link_to 'Edit', edit_food_item_path(food_item)
        %td= link_to 'Destroy', food_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Food item', new_food_item_path, class: "btn btn-secondary"

app/views/food_items/new.html.haml
%h1 New food_item

= render 'form'

= link_to 'Back', food_items_path

app/views/food_items/show.html.haml
%p#notice= notice

.col-xs-12
  .col-xs-6
    .card.card-inverse
      %img.card-img{:alt => "Food Image", "src" => "#{@food_item.image_url}", :width => "100%"}
      .card-img-overlay
        %h1.card-title 
          = @food_item.name


    %table.table.table-striped.table-condensed
      %tr
        %td
          %b Description
        %td= @food_item.description
      %tr
        %td 
          %b Price
        %td= @food_item.price.round
      %tr
        %td 
          %b Section
        %td= @food_item.section
      %tr
        %td 
          %b Views
        %td= @food_item.impressionist_count

  .col-xs-6
    %h3
      Reviews
      .pull-right
        = button_to "Add a Review", new_food_item_review_path(@food_item), :method => :get, class: 'btn btn-success'

    Average Rating
    .average-review-rating{"data-score" => @average_review}
      = @average_review

    %br
    = render @food_item.reviews

= link_to 'Order', new_food_item_order_path(@food_item), class: "btn btn-success"
\|
= link_to 'Edit', edit_food_item_path(@food_item), class: "btn btn-primary"
\|
= link_to 'Delete', food_item_path, class: "btn btn-danger", :method => :delete, :data => { :confirm => 'Are you sure?' } 
\|
= link_to 'Back', food_items_path, class: "btn btn-secondary"


:javascript
  $('.review-rating').raty({
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  },
  path: '/assets/'
  // somehow this needs to be placed in here and the review partial?!?
  });

:javascript
  $('.average-review-rating').raty({
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  },
  path: '/assets/'
  });