config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :food_items, only: [:index, :create, :destroy, :update]
    end
  end

  resources :food_items do
    resources :orders
    resources :reviews
  end

  resources :welcome
  
  resources :menu do
    collection do
      get :lowhighprice 
      get :highlowprice
      get :abc
    end
  end
  
  get 'menu' => 'menu#index'
  get 'contact_us' => 'welcome#contact_us'
  get 'react' => 'welcome#react'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_food_item

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @food_item.reviews << @review
    
    if @review.save
      redirect_to food_item_path(@food_item)
    else 
      render 'new'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to food_item_path(@food_item)
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to food_item_path(@food_item)
  end

  private
  	def review_params
  	  params.require(:review).permit(:rating, :rev)
    end

    def find_food_item
  	  @food_item = FoodItem.find(params[:food_item_id])
    end

end

app/views/reviews/_form.html.haml
= simple_form_for([@food_item, @food_item.reviews.build]) do |f|
	#rating-form
		= f.input :rating
	%br
	= f.input :rev, :label => "Review"	
	= f.submit "Submit Review", class: "btn btn-default"

/ = f.hidden_field :food_item_id, value: @food_item.id

:javascript
	$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
	});

app/views/reviews/_review.html.haml
.card
  .card-title
    .col-xs-6
      %b Stars:
      = review.rating
      .review-rating{"data-score" => review.rating}
    .col-xs-6.col-right
      = link_to 'Edit', edit_food_item_review_path(review.food_item, review), class: 'btn btn-secondary'
      = link_to 'Delete', food_item_review_path(review.food_item, review), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-secondary'
  .card-block
    %p.card-text
      = review.rev
      %br


:javascript
  $('.review-rating').raty({
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  },
  path: '/assets/'
  });  

app/views/reviews/edit.html.haml
%h2 Edit Review
= simple_form_for([@food_item, @review]) do |f|
	.col-md-6
		%b Rating
		#rating-form
		%br
		= f.input :rating
		= f.input :rev, :label => "Review"
		= f.button :submit
	.col-md-6
		= image_tag(@food_item.image_url)

:javascript
	$('#rating-form').raty({
	// path: '/assets/',
	scoreName: 'review[rating]'
	});

app/views/reviews/new.html.haml
.col-xs-12.col-md-6
	%h3 New Review
	= render 'form'
%br
.col-xs-12.col-md-6
	= image_tag(@food_item.image_url, :size => "150", :class => "img-responsive" )